package api

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/go-go-golems/gotest-agent/internal/ai"
	"github.com/go-go-golems/gotest-agent/internal/config"
	"github.com/go-go-golems/gotest-agent/internal/db"
	"github.com/go-go-golems/gotest-agent/internal/drift"
	"github.com/go-go-golems/gotest-agent/internal/webhook"
)

func TestDriftEndpoints(t *testing.T) {
	s := NewServer(&config.Config{MaxConcurrentRuns: 1, AppEnv: "development"}, db.NewMemoryStore(), nil)

	created := s.drifts.Add(drift.Drift{
		Repository: "acme/app",
		Type:       drift.TypeMissingTest,
		FilePath:   "internal/api/server.go",
		Severity:   drift.SeverityHigh,
	})

	req := httptest.NewRequest(http.MethodGet, "/api/v1/drifts?repository=acme/app", nil)
	rec := httptest.NewRecorder()
	s.router.ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Fatalf("GET /drifts status = %d", rec.Code)
	}
	var list []drift.Drift
	if err := json.NewDecoder(rec.Body).Decode(&list); err != nil {
		t.Fatalf("decode list: %v", err)
	}
	if len(list) != 1 || list[0].ID != created.ID {
		t.Fatalf("expected 1 drift with ID %s, got %+v", created.ID, list)
	}

	body := strings.NewReader(`{"status":"fixed"}`)
	req = httptest.NewRequest(http.MethodPatch, "/api/v1/drifts/"+created.ID, body)
	rec = httptest.NewRecorder()
	s.router.ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Fatalf("PATCH /drifts/{id} status = %d, body = %s", rec.Code, rec.Body.String())
	}
	var updated drift.Drift
	if err := json.NewDecoder(rec.Body).Decode(&updated); err != nil {
		t.Fatalf("decode updated: %v", err)
	}
	if updated.Status != drift.StatusFixed {
		t.Fatalf("expected status fixed, got %s", updated.Status)
	}

	req = httptest.NewRequest(http.MethodPatch, "/api/v1/drifts/nope", strings.NewReader(`{"status":"fixed"}`))
	rec = httptest.NewRecorder()
	s.router.ServeHTTP(rec, req)
	if rec.Code != http.StatusNotFound {
		t.Fatalf("expected 404 for unknown drift, got %d", rec.Code)
	}
}

func TestDetectDriftFromPush(t *testing.T) {
	s := NewServer(&config.Config{MaxConcurrentRuns: 1}, db.NewMemoryStore(), nil)

	s.detectDriftFromPush(webhook.PushEvent{
		Ref:        "refs/heads/main",
		Repository: webhook.Repository{FullName: "acme/app"},
		Commits: []webhook.Commit{
			{ID: "abc", Modified: []string{"internal/service/user.go"}},
		},
	})

	list := s.drifts.List("acme/app", drift.TypeMissingTest, "")
	if len(list) != 1 {
		t.Fatalf("expected 1 missing_test drift, got %d", len(list))
	}
	if list[0].FilePath != "internal/service/user.go" {
		t.Fatalf("unexpected file path: %s", list[0].FilePath)
	}
}

func TestDetectDriftFromPushAutoGeneratesTests(t *testing.T) {
	t.Setenv("GOTEST_AI_PLANNING", "1")

	s := NewServer(&config.Config{
		MaxConcurrentRuns:      1,
		AutoGenerateDriftTests: true,
		MaxAutoGenerateDrifts:  5,
	}, db.NewMemoryStore(), nil)

	s.aiClientFn = func(ctx context.Context) ai.Client {
		return &mockAIClient{out: "```go\npackage service\n```\nConfidence: 90"}
	}

	s.detectDriftFromPush(webhook.PushEvent{
		Ref:        "refs/heads/main",
		Repository: webhook.Repository{FullName: "acme/app"},
		Commits: []webhook.Commit{
			{ID: "abc", Modified: []string{"internal/service/user.go", "internal/service/order.go"}},
		},
	})

	drifts := s.drifts.List("acme/app", drift.TypeMissingTest, "")
	if len(drifts) != 2 {
		t.Fatalf("expected 2 missing_test drifts, got %d", len(drifts))
	}

	time.Sleep(200 * time.Millisecond)

	for _, d := range drifts {
		if got := len(s.driftTests.ByDrift(d.ID)); got != 1 {
			t.Errorf("expected 1 generated test for %s, got %d", d.ID, got)
		}
	}

	events := s.events.GetEvents("acme/app")
	if len(events) != 2 {
		t.Fatalf("expected 2 drift_test_generated events, got %d", len(events))
	}
}

func TestDetectDriftFromPushAutoGenerationDisabled(t *testing.T) {
	t.Setenv("GOTEST_AI_PLANNING", "1")

	s := NewServer(&config.Config{
		MaxConcurrentRuns:      1,
		AutoGenerateDriftTests: false,
	}, db.NewMemoryStore(), nil)

	s.aiClientFn = func(ctx context.Context) ai.Client {
		return &mockAIClient{out: "```go\npackage service\n```\nConfidence: 90"}
	}

	s.detectDriftFromPush(webhook.PushEvent{
		Ref:        "refs/heads/main",
		Repository: webhook.Repository{FullName: "acme/app"},
		Commits: []webhook.Commit{
			{ID: "abc", Modified: []string{"internal/service/user.go"}},
		},
	})

	drifts := s.drifts.List("acme/app", drift.TypeMissingTest, "")
	if len(drifts) != 1 {
		t.Fatalf("expected 1 drift, got %d", len(drifts))
	}
	if got := len(s.driftTests.ByDrift(drifts[0].ID)); got != 0 {
		t.Errorf("expected 0 generated tests when disabled, got %d", got)
	}
}

func TestDetectDriftFromPushLimitsAutoGeneration(t *testing.T) {
	t.Setenv("GOTEST_AI_PLANNING", "1")

	s := NewServer(&config.Config{
		MaxConcurrentRuns:      1,
		AutoGenerateDriftTests: true,
		MaxAutoGenerateDrifts:  1,
	}, db.NewMemoryStore(), nil)

	calls := 0
	s.aiClientFn = func(ctx context.Context) ai.Client {
		return &mockAIClient{out: "```go\npackage service\n```\nConfidence: 90"}
	}
	_ = calls

	s.detectDriftFromPush(webhook.PushEvent{
		Ref:        "refs/heads/main",
		Repository: webhook.Repository{FullName: "acme/app"},
		Commits: []webhook.Commit{
			{ID: "abc", Modified: []string{"internal/service/a.go", "internal/service/b.go", "internal/service/c.go"}},
		},
	})

	time.Sleep(200 * time.Millisecond)

	totalGenerated := 0
	for _, d := range s.drifts.List("acme/app", "", "") {
		totalGenerated += len(s.driftTests.ByDrift(d.ID))
	}
	if totalGenerated != 1 {
		t.Fatalf("expected 1 generated test with limit 1, got %d", totalGenerated)
	}
}

func TestAutoGenerateDriftTestEndpoint(t *testing.T) {
	t.Setenv("GOTEST_AI_PLANNING", "1")

	s := NewServer(&config.Config{MaxConcurrentRuns: 1}, db.NewMemoryStore(), nil)
	d := s.drifts.Add(drift.Drift{Repository: "acme/app", Type: drift.TypeMissingTest, FilePath: "a.go", Severity: drift.SeverityHigh})

	s.aiClientFn = func(ctx context.Context) ai.Client {
		return &mockAIClient{out: "```go\npackage a\n```\nConfidence: 90"}
	}

	req := httptest.NewRequest(http.MethodGet, "/api/v1/drifts/"+d.ID+"/auto-generate", nil)
	rec := httptest.NewRecorder()
	s.router.ServeHTTP(rec, req)
	if rec.Code != http.StatusCreated {
		t.Fatalf("expected 201, got %d: %s", rec.Code, rec.Body.String())
	}

	if got := len(s.driftTests.ByDrift(d.ID)); got != 1 {
		t.Fatalf("expected 1 generated test, got %d", got)
	}
}

func TestAutoGenerateDriftTestEndpointDisabledWithoutAI(t *testing.T) {
	t.Setenv("GOTEST_AI_PLANNING", "")
	s := NewServer(&config.Config{MaxConcurrentRuns: 1}, db.NewMemoryStore(), nil)
	d := s.drifts.Add(drift.Drift{Repository: "acme/app", Type: drift.TypeMissingTest, FilePath: "a.go", Severity: drift.SeverityHigh})

	req := httptest.NewRequest(http.MethodGet, "/api/v1/drifts/"+d.ID+"/auto-generate", nil)
	rec := httptest.NewRecorder()
	s.router.ServeHTTP(rec, req)
	if rec.Code != http.StatusServiceUnavailable {
		t.Fatalf("expected 503 without AI, got %d", rec.Code)
	}
}

func TestAutoGenerateDriftTestEndpointUnknownDrift(t *testing.T) {
	t.Setenv("GOTEST_AI_PLANNING", "1")
	s := NewServer(&config.Config{MaxConcurrentRuns: 1}, db.NewMemoryStore(), nil)

	req := httptest.NewRequest(http.MethodGet, "/api/v1/drifts/nope/auto-generate", nil)
	rec := httptest.NewRecorder()
	s.router.ServeHTTP(rec, req)
	if rec.Code != http.StatusNotFound {
		t.Fatalf("expected 404 for unknown drift, got %d", rec.Code)
	}
}

// mockAIClient is a minimal ai.Client implementation for tests.
type mockAIClient struct {
	out string
	err error
}

func (m *mockAIClient) GenerateText(ctx context.Context, prompt string) (string, error) {
	return m.out, m.err
}

func (m *mockAIClient) GenerateWithImage(ctx context.Context, prompt, imageBase64 string) (string, error) {
	return m.out, m.err
}
