package api

import (
	"context"
	"encoding/json"
	"net/http"
	"path/filepath"
	"strings"

	"github.com/go-chi/chi/v5"
	"github.com/go-go-golems/gotest-agent/internal/ai"
	"github.com/go-go-golems/gotest-agent/internal/config"
	"github.com/go-go-golems/gotest-agent/internal/drift"
	"github.com/go-go-golems/gotest-agent/internal/events"
	"github.com/go-go-golems/gotest-agent/internal/notify"
	"github.com/go-go-golems/gotest-agent/internal/webhook"
)

// handleListDrifts returns drift records, filterable by ?repository=, ?type=, ?status=.
func (s *Server) handleListDrifts(w http.ResponseWriter, r *http.Request) {
	q := r.URL.Query()
	list := s.drifts.List(q.Get("repository"), q.Get("type"), q.Get("status"))
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(list)
}

// handleUpdateDriftStatus updates a drift's status (pending, fixed, ignored).
func (s *Server) handleUpdateDriftStatus(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")
	var body struct {
		Status string `json:"status"`
	}
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		http.Error(w, "invalid JSON body", http.StatusBadRequest)
		return
	}
	updated, err := s.drifts.UpdateStatus(id, body.Status)
	if err != nil {
		status := http.StatusBadRequest
		if strings.Contains(err.Error(), "not found") {
			status = http.StatusNotFound
		}
		http.Error(w, err.Error(), status)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(updated)
}

// aiClientForDrift returns the LLM client, preferring the test hook if set.
func (s *Server) aiClientForDrift(ctx context.Context) ai.Client {
	if s.aiClientFn != nil {
		return s.aiClientFn(ctx)
	}
	return s.aiClient(ctx)
}

// detectDriftFromPush runs drift detection for a GitHub push event using the
// changed-file lists from its commits. Detected drifts are forwarded to the
// alert notification engine. When AI planning is enabled and auto-generation is
// configured, it also asynchronously generates tests for the first N eligible
// high-severity missing_test drifts so the webhook response is not blocked.
func (s *Server) detectDriftFromPush(event webhook.PushEvent) {
	var added, modified, removed []string
	for _, c := range event.Commits {
		added = append(added, c.Added...)
		modified = append(modified, c.Modified...)
		removed = append(removed, c.Removed...)
	}
	if len(added)+len(modified)+len(removed) == 0 {
		return
	}

	repoDir := ""
	base := filepath.Clean(webhookCloneDir)
	dir := filepath.Clean(filepath.Join(base, event.Repository.FullName))
	if dir != base && strings.HasPrefix(dir, base+string(filepath.Separator)) {
		repoDir = dir
	}

	newDrifts := s.driftDetector.DetectDrift(event.Repository.FullName, repoDir, added, modified, removed)

	if len(newDrifts) > 0 {
		cfg := s.cfg
		if cfg == nil {
			cfg = &config.Config{}
		}
		_ = cfg
		notify.BatchNotifyDrift(newDrifts, nil)
	}

	if !s.cfg.AutoGenerateDriftTests {
		return
	}
	llm := s.aiClientForDrift(context.Background())
	if llm == nil {
		return
	}

	candidates := filterAutoGenerateCandidates(newDrifts)
	limit := s.cfg.MaxAutoGenerateDrifts
	if limit <= 0 {
		limit = 5
	}
	if len(candidates) > limit {
		candidates = candidates[:limit]
	}
	if len(candidates) == 0 {
		return
	}

	gen := drift.NewGenerator(llm, s.driftTests)
	batch := drift.NewBatchGenerator(gen, limit, s.driftEventEmitter())

	// Run asynchronously so the webhook response is not blocked.
	go batch.GenerateBatch(context.Background(), event.Repository.FullName, candidates)
}

func filterAutoGenerateCandidates(drifts []drift.Drift) []drift.Drift {
	var candidates []drift.Drift
	for _, d := range drifts {
		if d.Status == drift.StatusPending && d.Type == drift.TypeMissingTest && d.Severity == drift.SeverityHigh {
			candidates = append(candidates, d)
		}
	}
	return candidates
}

// handleAutoGenerateDriftTest manually triggers auto-generation for a single
// drift. GET /api/v1/drifts/{id}/auto-generate
func (s *Server) handleAutoGenerateDriftTest(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")
	gt, err := s.generateDriftTest(r.Context(), id, true)
	if err != nil {
		status := http.StatusInternalServerError
		switch {
		case err == errDriftNotFound:
			status = http.StatusNotFound
		case err == errAIDisabled:
			status = http.StatusServiceUnavailable
		case strings.Contains(err.Error(), "cannot auto-generate"):
			status = http.StatusUnprocessableEntity
		}
		http.Error(w, err.Error(), status)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	json.NewEncoder(w).Encode(gt)
}

// driftEventEmitter returns an EventEmitter backed by the server's event bus.
func (s *Server) driftEventEmitter() drift.EventEmitter {
	return &serverDriftEventEmitter{events: s.events}
}

type serverDriftEventEmitter struct {
	events *events.Store
}

func (e *serverDriftEventEmitter) EmitDriftTestGenerated(ctx context.Context, runID string, d drift.Drift, gt *drift.GeneratedTest) {
	if e.events == nil {
		return
	}
	e.events.Emit(runID, events.EventType("drift_test_generated"), "auto_generate", "Auto-generated test for drift", map[string]string{
		"drift_id":   d.ID,
		"test_id":    gt.ID,
		"test_name":  gt.TestName,
		"repository": d.Repository,
		"file_path":  d.FilePath,
	})
}

func (e *serverDriftEventEmitter) EmitDriftTestGenerationFailed(ctx context.Context, runID string, d drift.Drift, err error) {
	if e.events == nil {
		return
	}
	msg := "Auto-generation failed for drift"
	if err != nil {
		msg = msg + ": " + err.Error()
	}
	e.events.Emit(runID, events.EventType("drift_test_generation_failed"), "auto_generate", msg, map[string]string{
		"drift_id":   d.ID,
		"repository": d.Repository,
		"file_path":  d.FilePath,
	})
}
