package api

import (
	"context"
	"testing"
	"time"

	"github.com/go-go-golems/gotest-agent/internal/ai"
	"github.com/go-go-golems/gotest-agent/internal/config"
	"github.com/go-go-golems/gotest-agent/internal/db"
	"github.com/go-go-golems/gotest-agent/internal/drift"
	"github.com/go-go-golems/gotest-agent/internal/webhook"
)

func TestProcessPushWithTestGenDisabledWithoutAIPlanning(t *testing.T) {
	t.Setenv("GOTEST_AI_PLANNING", "")
	store := db.NewMemoryStore()
	s := NewServer(&config.Config{MaxConcurrentRuns: 1}, store, nil)

	event := webhook.PushEvent{
		Ref:        "refs/heads/main",
		Repository: webhook.Repository{FullName: "acme/app", CloneURL: "https://example.com/acme/app.git"},
	}
	if s.processPushWithTestGen(event) {
		t.Fatal("expected fallback path when AI planning is disabled")
	}

	runs, err := store.ListRuns(context.Background(), 10, 0)
	if err != nil {
		t.Fatal(err)
	}
	if len(runs) != 0 {
		t.Fatalf("test-gen skip must not create runs, got %d", len(runs))
	}
}

func TestPushWebhookAutoGeneratesDriftTests(t *testing.T) {
	t.Setenv("GOTEST_AI_PLANNING", "1")

	store := db.NewMemoryStore()
	s := NewServer(&config.Config{
		MaxConcurrentRuns:      1,
		AutoGenerateDriftTests: true,
		MaxAutoGenerateDrifts:  5,
	}, store, nil)
	s.aiClientFn = func(ctx context.Context) ai.Client {
		return &mockAIClient{out: "```go\npackage service\n```\nConfidence: 90"}
	}

	// Simulate the webhook push path: drift detection then auto-generation.
	s.detectDriftFromPush(webhook.PushEvent{
		Ref:        "refs/heads/main",
		Repository: webhook.Repository{FullName: "acme/app", CloneURL: "https://example.com/acme/app.git"},
		Commits: []webhook.Commit{
			{ID: "abc", Modified: []string{"internal/service/user.go"}},
		},
	})

	list := s.drifts.List("acme/app", drift.TypeMissingTest, "")
	if len(list) != 1 {
		t.Fatalf("expected 1 missing_test drift, got %d", len(list))
	}

	time.Sleep(200 * time.Millisecond)

	if got := len(s.driftTests.ByDrift(list[0].ID)); got != 1 {
		t.Fatalf("expected 1 generated test, got %d", got)
	}
}

func TestPushWebhookNoAutoGenerationWhenDisabled(t *testing.T) {
	t.Setenv("GOTEST_AI_PLANNING", "1")

	store := db.NewMemoryStore()
	s := NewServer(&config.Config{
		MaxConcurrentRuns:      1,
		AutoGenerateDriftTests: false,
	}, store, nil)
	s.aiClientFn = func(ctx context.Context) ai.Client {
		return &mockAIClient{out: "```go\npackage service\n```\nConfidence: 90"}
	}

	s.detectDriftFromPush(webhook.PushEvent{
		Ref:        "refs/heads/main",
		Repository: webhook.Repository{FullName: "acme/app", CloneURL: "https://example.com/acme/app.git"},
		Commits: []webhook.Commit{
			{ID: "abc", Modified: []string{"internal/service/user.go"}},
		},
	})

	list := s.drifts.List("acme/app", drift.TypeMissingTest, "")
	if len(list) != 1 {
		t.Fatalf("expected 1 drift, got %d", len(list))
	}

	time.Sleep(50 * time.Millisecond)

	if got := len(s.driftTests.ByDrift(list[0].ID)); got != 0 {
		t.Fatalf("expected 0 generated tests when disabled, got %d", got)
	}
}
