ALTER TABLE projects ADD COLUMN IF NOT EXISTS test_type VARCHAR(20);
ALTER TABLE projects ADD COLUMN IF NOT EXISTS base_url TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS environment VARCHAR(100);
ALTER TABLE projects ADD COLUMN IF NOT EXISTS spec TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS api_docs TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS auth_type VARCHAR(50);
ALTER TABLE projects ADD COLUMN IF NOT EXISTS credentials TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS focus_hints TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS skip_hints TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS feature_map JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_projects_created ON projects(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_projects_test_type ON projects(test_type);
