// Package config memuat konfigurasi aplikasi dari environment variables
package config

import (
	"os"
	"strings"
)

// Config menyimpan semua konfigurasi yang dibutuhkan aplikasi
type Config struct {
	AppPort                string // Port HTTP server (default: 8080)
	AppEnv                 string // Environment: development, production (default: development)
	APIKey                 string // API key untuk autentikasi (kosong = tanpa auth)
	CORSAllowedOrigins     string // Daftar origin CORS dipisah koma (kosong/"*" = wildcard, development)
	GitHubWebhookSecret    string // Secret verifikasi HMAC webhook GitHub
	JWTSecret              string // Secret untuk JWT cookie auth dashboard
	DatabaseURL            string // URL koneksi PostgreSQL
	RedisURL               string // Alamat Redis untuk job queue
	QueueEnabled           bool   // Aktifkan durable job queue Redis/Asynq (default: false, in-process goroutines)
	AnthropicAPIKey        string // API key Anthropic untuk LLM (fallback ketika LLM_API_KEY kosong)
	LLMModel               string // Model LLM yang digunakan (default: claude-sonnet-4-5)
	LLMProvider            string // Provider LLM: anthropic, openai, google, deepseek, etc.
	LLMBaseURL             string // Base URL untuk OpenAI-compatible endpoint
	LLMFallbackProvider    string // Provider cadangan jika utama gagal (kosong = nonaktif)
	LLMFallbackModel       string // Model untuk provider cadangan
	LLMFallbackAPIKey      string // API key untuk provider cadangan
	LLMFallbackBaseURL     string // Base URL untuk provider cadangan
	SteelAPIURL            string // URL Steel Browser API
	SteelAPIKey            string // API key Steel Browser (opsional)
	SteelMaxSessions       int    // Maksimal sesi browser bersamaan
	BrowserAllowedHosts    string // Comma-separated explicit allowlist for browser egress to local/private hosts
	MaxConcurrentRuns      int    // Maksimal concurrent test run goroutines (default: 10)
	LangGraphURL           string // URL LangGraph sidecar
	MaxFixAttempts         int    // Maksimal percobaan fix test gagal
	TimeoutSeconds         int    // Timeout eksekusi test (detik)
	RunTimeoutSeconds      int    // Timeout total satu run (detik); watchdog agar run hang tidak "running" selamanya (default: 1200)
	ScreenshotsPath        string // Direktori penyimpanan screenshot
	ReportsPath            string // Direktori penyimpanan laporan HTML
	TracingEnabled         bool   // Enable distributed tracing (OTLP)
	TracingEndpoint        string // OTLP gRPC endpoint (default: localhost:4317)
	ServiceVersion         string // Service version for tracing (default: 1.0.0)
	AutoGenerateDriftTests bool   // Auto-generate tests for high-severity missing_test drifts on push (default: true)
	MaxAutoGenerateDrifts  int    // Maximum number of drifts to auto-generate tests for per push (default: 5)
}

// normalizeOTLPEndpoint strips an http(s):// or otlp:// scheme prefix from an
// OTLP endpoint. The gRPC exporter appends its own port and treats the value as
// a bare host:port; leaving the scheme in produces e.g. "http://jaeger:4317:443"
// which fails with "too many colons in address".
func normalizeOTLPEndpoint(v string) string {
	for _, prefix := range []string{"https://", "http://", "otlp://"} {
		if strings.HasPrefix(v, prefix) {
			return strings.TrimPrefix(v, prefix)
		}
	}
	return v
}

// Load membaca konfigurasi dari environment variables dengan nilai default
func Load() *Config {
	return &Config{
		AppPort:                getEnv("APP_PORT", "8080"),
		AppEnv:                 getEnv("APP_ENV", "development"),
		APIKey:                 getEnv("API_KEY", ""),
		CORSAllowedOrigins:     getEnv("CORS_ALLOWED_ORIGINS", ""),
		GitHubWebhookSecret:    getEnv("GITHUB_WEBHOOK_SECRET", ""),
		JWTSecret:              getEnv("JWT_SECRET", ""),
		DatabaseURL:            getEnv("DATABASE_URL", "postgres://postgres:password@localhost:5432/gotest_agent?sslmode=disable"),
		RedisURL:               getEnv("REDIS_URL", "localhost:6379"),
		QueueEnabled:           getEnv("QUEUE_ENABLED", "") == "true",
		AnthropicAPIKey:        getEnv("ANTHROPIC_API_KEY", ""),
		LLMModel:               getEnv("LLM_MODEL", "claude-sonnet-4-5"),
		LLMProvider:            getEnv("LLM_PROVIDER", "anthropic"),
		LLMBaseURL:             getEnv("LLM_BASE_URL", ""),
		LLMFallbackProvider:    getEnv("LLM_FALLBACK_PROVIDER", ""),
		LLMFallbackModel:       getEnv("LLM_FALLBACK_MODEL", ""),
		LLMFallbackAPIKey:      getEnv("LLM_FALLBACK_API_KEY", ""),
		LLMFallbackBaseURL:     getEnv("LLM_FALLBACK_BASE_URL", ""),
		SteelAPIURL:            getEnv("STEEL_API_URL", "http://localhost:3000"),
		SteelAPIKey:            getEnv("STEEL_API_KEY", ""),
		SteelMaxSessions:       getEnvInt("STEEL_MAX_SESSIONS", 10),
		BrowserAllowedHosts:    getEnv("BROWSER_ALLOWED_HOSTS", ""),
		MaxConcurrentRuns:      getEnvInt("MAX_CONCURRENT_RUNS", 10),
		LangGraphURL:           getEnv("LANGGRAPH_URL", "http://localhost:8000"),
		MaxFixAttempts:         getEnvInt("MAX_FIX_ATTEMPTS", 3),
		TimeoutSeconds:         getEnvInt("DEFAULT_TIMEOUT_SECONDS", 300),
		RunTimeoutSeconds:      getEnvInt("RUN_TIMEOUT_SECONDS", 600),
		ScreenshotsPath:        getEnv("SCREENSHOTS_PATH", "./data/screenshots"),
		ReportsPath:            getEnv("REPORTS_PATH", "./data/reports"),
		TracingEnabled:         getEnv("TRACING_ENABLED", "false") == "true",
		TracingEndpoint:        normalizeOTLPEndpoint(getEnv("OTEL_EXPORTER_OTLP_ENDPOINT", "localhost:4317")),
		ServiceVersion:         getEnv("SERVICE_VERSION", "1.0.0"),
		AutoGenerateDriftTests: getEnv("AUTO_GENERATE_DRIFT_TESTS", "true") == "true",
		MaxAutoGenerateDrifts:  getEnvInt("MAX_AUTO_GENERATE_DRIFTS", 5),
	}
}

// getEnv membaca env var, gunakan fallback jika kosong
func getEnv(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

// getEnvInt reads an integer environment variable, returning fallback if unset or invalid.
func getEnvInt(key string, fallback int) int {
	v := os.Getenv(key)
	if v == "" {
		return fallback
	}
	n := 0
	for _, c := range v {
		if c < '0' || c > '9' {
			return fallback
		}
		n = n*10 + int(c-'0')
	}
	if n < 1 {
		return fallback
	}
	return n
}
